
services:
  - type: web
    name: laravel12-app
    env: docker
    plan: free
    repo: git@github.com:616ZaikoSKZ/laravel.git
    region: oregon
    buildCommand: "echo 'Dockerfile already handles build'"
    startCommand: "echo 'Dockerfile already handles start'"
